### ISSUE TITLE
babel-plugin-react-css-modulesの導入方法を知る

### ISSUE THREAD

**Issue by syunto07ka** [syunto07ka/jewelry_box#20]
<img width="1127" alt="スクリーンショット 2020-04-02 0 06 50" src="https://user-images.githubusercontent.com/37825725/78153347-ecbc9900-7475-11ea-9a23-aeca0824b3d7.png">
<img width="421" alt="スクリーンショット 2020-04-02 0 07 10" src="https://user-images.githubusercontent.com/37825725/78153356-efb78980-7475-11ea-8a35-88c32ae5d3a8.png">

**Comment by Syunto07ka** [comment]
https://github.com/gajus/babel-plugin-react-css-modules#how-does-it-work

<img width="948" alt="スクリーンショット 2020-04-12 13 32 03" src="https://user-images.githubusercontent.com/37825725/79060601-09e93700-7cc2-11ea-8deb-a5560b61f327.png">

**Comment by Syunto07ka** [comment]
エラーなった

<img width="1130" alt="スクリーンショット 2020-04-12 14 04 14" src="https://user-images.githubusercontent.com/37825725/79061161-3d2ec480-7cc8-11ea-8cb3-1bcc63d81321.png">


https://github.com/gajus/babel-plugin-react-css-modules/issues/41

**Comment by Syunto07ka** [comment]
エラー変わった。

```
Failed to compile.

./src/index.tsx
Error: /Users/syunto/development/jewelry_box/src/index.tsx: Cannot find module 'postcss-scss'
Require stack:
- /Users/syunto/development/jewelry_box/node_modules/babel-plugin-react-css-modules/dist/requireCssModule.js
- /Users/syunto/development/jewelry_box/node_modules/babel-plugin-react-css-modules/dist/index.js
- /Users/syunto/development/jewelry_box/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/syunto/development/jewelry_box/node_modules/@babel/core/lib/config/files/index.js
- /Users/syunto/development/jewelry_box/node_modules/@babel/core/lib/index.js
- /Users/syunto/development/jewelry_box/node_modules/babel-loader/lib/index.js
- /Users/syunto/development/jewelry_box/node_modules/loader-runner/lib/loadLoader.js
- /Users/syunto/development/jewelry_box/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/syunto/development/jewelry_box/node_modules/webpack/lib/NormalModule.js
- /Users/syunto/development/jewelry_box/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/syunto/development/jewelry_box/node_modules/webpack/lib/Compiler.js
- /Users/syunto/development/jewelry_box/node_modules/webpack/lib/webpack.js
- /Users/syunto/development/jewelry_box/scripts/start.js
 ~/development/jewelry_box  add_babel_plugin_react_css_modules●●  0m                                                                                                                                 
```

以下２つの設定ファイルをいじった

```
webpack.config.js

{
        loader: require.resolve('css-loader'),
        options: {
          ...cssOptions,
          localIdentName: "[path]___[name]__[local]___[hash:base64:5]",
          modules: true
        },
      },
```

```
package.json

"babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      [
				"react-css-modules",
				{
					"filetypes": {
            ".scss": {
              "syntax": "postcss-scss"
            }
					}
				}
			]
    ]
  },
```

**Comment by Syunto07ka** [comment]
エラー変わった

<img width="1075" alt="スクリーンショット 2020-04-12 20 22 15" src="https://user-images.githubusercontent.com/37825725/79067582-543ada00-7cfb-11ea-9790-2d99f356a981.png">

解決策これかな
https://github.com/rails/webpacker/issues/2197

css-loaderのwebpack設定の方法が変わってるらしい

https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#300-2019-06-11

<img width="982" alt="スクリーンショット 2020-04-12 20 22 09" src="https://user-images.githubusercontent.com/37825725/79067597-6fa5e500-7cfb-11ea-8cd0-ff064a8f70e8.png">

**Comment by Syunto07ka** [comment]
上のに加えて、typescriptのerror出てた。

styleName型にないよって言われてて

```
npm install --save @types/react-css-modules
```

これやったら解決(まあそりゃそうだなと)

```
import React from 'react';
import logo from './logo.svg';
import './App.scss';

function App() {
  return (
    <div styleName="app">
      <header styleName="appHeader">
        <img src={logo} styleName="appLogo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          styleName="appLink"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;

```

で無事表示

<img width="1351" alt="スクリーンショット 2020-04-12 20 34 17" src="https://user-images.githubusercontent.com/37825725/79067829-50a85280-7cfd-11ea-8ddf-e8fd0efed28b.png">

**Comment by Syunto07ka** [comment]
#48 にて導入方法はわかったのでこのissueはclose

**Comment by piro0919** [comment]
まだ解決できていないのにcloseしないでくださーい 🙅‍♂️

**Comment by syunto07ka** [comment]
🙇

**Comment by piro0919** [comment]
rel https://github.com/syunto07ka/jewelry_box/issues/54

**Comment by piro0919** [comment]
@syunto07ka 

#54 でかなり理解されたと思うので、ここまできたら導入してしまって問題ないと思います。
素の css modules と違いきちんと linter に沿えるようになるため、導入して損はないかと。
