### ISSUE TITLE
npm run ejectによる実行前と実行後差分の違いをまとめる

### ISSUE THREAD

**Issue by Syunto07ka** [Syunto07ka/jewelry_box#24]
rel #12 #22

**Comment by piro0919** [comment]
@Syunto07ka 

あとで確認しまーす

**Comment by Syunto07ka** [comment]
@piro0919 
> いくつかポイントを挙げるので、確認できたらcloseでいいんじゃないでしょうか 👍

ともあるので、閉じちゃいますね。
なにかあれば以下にコメントいただければとmm

**Comment by piro0919** [comment]
@Syunto07ka 

すいません忘れてました。 🙇 

とはいえ、内容問題なさそうですー。
