### ISSUE TITLE
git flow、github flowについて調べる

### ISSUE THREAD

**Issue by syunto07ka** [syunto07ka/jewelry_box#26]
**Is your feature request related to a problem? Please describe.**
gitでの開発の最適化をしたい。そのための手法を学ぶ

**Describe the solution you'd like**
git flow, github flowをこのissueにまとめる。

**Additional context**
上げた手法とは別のものがあればそれも調べる

**Comment by syunto07ka** [comment]
https://nvie.com/posts/a-successful-git-branching-model/

**Comment by syunto07ka** [comment]
## main
https://nvie.com/posts/a-successful-git-branching-model/#the-main-branches

<img width="789" alt="スクリーンショット 2020-04-17 1 20 34" src="https://user-images.githubusercontent.com/37825725/79480999-e0296a80-8049-11ea-8062-c1e8a0533b78.png">

## surpport
https://nvie.com/posts/a-successful-git-branching-model/#supporting-branches

<img width="775" alt="スクリーンショット 2020-04-17 1 20 45" src="https://user-images.githubusercontent.com/37825725/79480939-c5ef8c80-8049-11ea-814d-bb6d27afd362.png">

**Comment by syunto07ka** [comment]
## github flow
https://guides.github.com/introduction/flow/

<img width="1134" alt="スクリーンショット 2020-04-17 1 30 25" src="https://user-images.githubusercontent.com/37825725/79481897-0d2a4d00-804b-11ea-8d9a-865a9c0ba00b.png">

**Comment by syunto07ka** [comment]
今の開発の感じだと、普通にgithub flowに則ってはいるのか。。？

**Comment by syunto07ka** [comment]
記事読んで簡単にissueまとめたのでcloseする

**Comment by piro0919** [comment]
@syunto07ka 

もうちょい書き下していきません…？
ドキュメントを読んで終わりでは、少し乱暴すぎる気がします。

正しい理解を持たれたか、ちょいと不安です。 🌵

**Comment by syunto07ka** [comment]
## git flow

### 動きについてざっくりと

### メリット

### デメリット

### どのようなケースでの採用が最適か

**Comment by syunto07ka** [comment]
## github flow

### 動きについてざっくりと

### メリット

### デメリット

### どのようなケースでの採用が最適か

**Comment by syunto07ka** [comment]
@piro0919 
まとめてみました！
間違っているところあれば正していただけるとmm

**Comment by piro0919** [comment]
@syunto07ka 

大体良さそうですが、少しだけ。

まず git flow のブランチ名がルールによって定められることは、個人的には大きなメリットだと思います。
むしろブランチ名で機能追加なのかバグフィックスなのかぱっとわからない github flow のほうがデメリットが大きいのでは？

あと、最適なケースについて git flow の見解が弱いですね。

git flow はとにかく厳格に進められるため、大規模なプロジェクトやしっかりとした運用が求められる場合に最適です。
特にブランチを以下のように振り分けれるのが強いと思っています。

- master → 本番環境
- release → production環境
- develop → 共有の開発環境
- feature → 個人の開発環境

production環境でe2eや結合テストを行うようなケースではかなりの威力を発揮する flow ですね。
ちなみに某社くらいの企業規模であれば git flow のほうが最適だと思いますが、採用は github flow なのが面白いです。

**Comment by piro0919** [comment]
参考サイトです。

- [git flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)
- [github flow](https://guides.github.com/introduction/flow/)

**Comment by syunto07ka** [comment]
> ちなみに某社くらいの企業規模であれば git flow のほうが最適だと思いますが、採用は github flow なのが面白いです

そうなんだ。。

**Comment by syunto07ka** [comment]
ではまとめられたということで、closeします！

**Comment by syunto07ka** [comment]
git flow、bitbucketのもあったんですね。
見ておきます👀
