### ISSUE TITLE
これから作るサイトの概要、設計について

### ISSUE THREAD

**Issue by syunto07ka** [syunto07ka/jewelry_box#40]
**Is your feature request related to a problem? Please describe.**
これから作るサイトを明確にイメージしたい

**Describe the solution you'd like**
- サイトの概要をまとめる
- サイトのデザインを行う

**Describe alternatives you've considered**
- 特になし

**Additional context**
- 概要に関してはこのIssueにまとめて終わり、と考えているが、ある程度まとまったらREADME.mdを更新してもよいかもしれない

- デザインはざっくりしたものを考えているが、もしできればfigmaなんかで作れるとよいかも

**Comment by Syunto07ka** [comment]
## milestone
- ルートページ(メインページ)の実装 rel #47 
- プロフィールページの実装 rel #46 
- 本番環境デプロイ(おそらくnetlify)

**Comment by syunto07ka** [comment]
デプロイ以降はまたissue立てて考えていく
このissueはclose
