### ISSUE TITLE
pagesディレクトリを切ってルートページを実装する

### ISSUE THREAD

**Issue by syunto07ka** [syunto07ka/jewelry_box#45]
**Is your feature request related to a problem? Please describe.**
パスごとにページが作れないので、その下準備が必要

**Describe the solution you'd like**
- src/containers/にpagesディレクトリを切って、ルートページを実装する
- src/containers/index.tsx にてルーティングの設定を行う

**Additional context**
おそらくreact-router-domを使うのだろうか

こんな記事発見
https://qiita.com/koja1234/items/486f7396ed9c2568b235

**Comment by Syunto07ka** [comment]
この記事ちょっと参考に
https://www.freecodecamp.org/news/react-router-in-5-minutes/
