### ISSUE TITLE
リセットCSSを導入する

### ISSUE THREAD

**Issue by piro0919** [syunto07ka/jewelry_box#51]
**Is your feature request related to a problem? Please describe.**
描画がブラウザやOSごとのクセに引っ張られるのはよろしくない

**Describe the solution you'd like**
リセットCSSの導入を考えてみてください

**Additional context**
ざっくりとで良いので、選定基準も書いてください 👍

**Comment by syunto07ka** [comment]
デフォルトでいい気がした。使い方簡単そう+公式が勧めている+css-loaderに適している
https://create-react-app.dev/docs/adding-css-reset/

styled-componentだとこっちを使うといいのか？
https://www.npmjs.com/package/react-style-reset

**Comment by syunto07ka** [comment]
ん、でもscssだとimportできなさそう。cssだといけるのか

**Comment by piro0919** [comment]
@syunto07ka 

> デフォルトでいい気がした。

せっかくなので勉強がてら、メジャーなリセットCSSを調べてみましょうか 👍

**Comment by syunto07ka** [comment]
見落としてた。。

**Comment by syunto07ka** [comment]
これよくまとまってそうですね👀

https://web-camp.io/magazine/archives/30817

**Comment by syunto07ka** [comment]
## Eric Meyer’s “Reset CSS” 2.0
### サイト
- https://meyerweb.com/eric/tools/css/reset/

特徴
- 全ての余白が消えてる
- 見出しとかも消えてる
- input要素はブラウザ固有のまま(<- これはよくない)
- コード量は結構簡素？

**Comment by syunto07ka** [comment]
@piro0919 
軽くまとめてみました！7つの中から3つ選んでざっくり書いてみました。
これを踏まえるとnormarize.cssかsanitize.cssが良いかなと思いました(ボタンとかリストとか見出しタグの大きさとかが変わってほしくないため)

ここちがうよ！とかこれまとめてないのだめ！とかあればご指摘を🙇

**Comment by piro0919** [comment]
@syunto07ka 

そこまで深く言及はしないですが、何点か

> コピペで使える。最初は必須でpackageのinstallをしないといけないかと思ってたけどそんなことはない。ただ同じ効果のあるCSSを読み込ませていればよいだけ。

コピペで使えるのは認識として正しいですが、パッケージ化されているものはパッケージを使うほうが個人的には良いかなーと思います
バージョン管理が面倒ですしね

> input要素はブラウザ固有のまま(<- これはよくない)

良くないことはないですね、ブラウザ固有のスタイルを残したいケースでは有用だと思います

> これを踏まえるとnormarize.cssかsanitize.cssが良いかなと思いました(ボタンとかリストとか見出しタグの大きさとかが変わってほしくないため)

実際のプロジェクトでは、こういった理由で選定することになると思います
余談ですが、個人的にはress推しだったりします

**Comment by syunto07ka** [comment]
> コピペで使えるのは認識として正しいですが、パッケージ化されているものはパッケージを使うほうが個人的には良いかなーと思います
> コピペだと個々人で修正可能な状態になってしまうので保守性に欠けますし、バージョン管理が面倒ですしね

まさに。今回はデフォルトのnormarize.cssを使いますが、別のreset cssを使う場合はpackageをinstallして運用すべきですかね

> ブラウザ固有のスタイルを使用したいケースでは有用だと思います

なんていうことがあるんですか！？(ないとは言い切れないけど)

**Comment by piro0919** [comment]
> なんていうことがあるんですか！？(ないとは言い切れないけど)

そこまで考えている現場にあたったことがないのでなんとも言えないですねー
ただ、ブラウザ固有のCSSが悪というわけでは決してないので、ケースバイケースだと思っていたほうが良いとは思いますね
