### ISSUE TITLE
ts及びtsxファイルに対してコードフォーマットをかける

### ISSUE THREAD

**Issue by piro0919** [syunto07ka/jewelry_box#52]
**Is your feature request related to a problem? Please describe.**
規約を守れていないコードを書いた場合でもcommitを上げることが可能な状態となっている

**Describe the solution you'd like**
huskyにコードフォーマットをかませる

**Additional context**
フォーマッターの選定はおまかせします 👍

**Comment by Syunto07ka** [comment]
これはコミットメッセージの話ではなく。。？

**Comment by piro0919** [comment]
@syunto07ka 

コミットメッセージは関係ないですよ。 👍 

単純に`prettier`とか`eslint`あたりの話ですね。

**Comment by syunto07ka** [comment]
issueのクローズ条件は

- Prettierのインストール
- huskyにgitのcommit時にコードフォーマットをする設定をする

ですかね

**Comment by piro0919** [comment]
@syunto07ka 

> huskyにgitのcommit時にコードフォーマットをする設定をする

こっちは認識あってます 👍 

> Prettierのインストール

こっちは prettier じゃなくても問題ないです
この前 eslint で完結させたいみたいなこと言われてませんでしたっけ？

**Comment by syunto07ka** [comment]
あまり知識ないときに言ってたことなので、もうちょっと調べてどうするか決めようかなと。
どこかでちらっとESLintとPrettierは使い分けたほうがよいと書いてあったのを見た気がした
