### ISSUE TITLE
react-router-domの<Route>に関してまとめる

### ISSUE THREAD

**Issue by syunto07ka** [syunto07ka/jewelry_box#53]
react-router-domに関してまとめる

rel https://github.com/Syunto07ka/jewelry_box/pull/49#discussion_r407238778

主にpropsの`component`と`children` の違いについてまとめる

**Comment by syunto07ka** [comment]
## component

https://reacttraining.com/react-router/core/api/Route/component

<img width="1129" alt="スクリーンショット 2020-04-15 1 35 11" src="https://user-images.githubusercontent.com/37825725/79251595-4df35c00-7ebb-11ea-8ba1-fec22bc3e2e0.png">

**Comment by syunto07ka** [comment]
## children

- `match`の内容を元に表示するか否かを決められる
- 上以外の点では`render`と同じ

<img width="921" alt="スクリーンショット 2020-04-15 2 20 28" src="https://user-images.githubusercontent.com/37825725/79254554-de33a000-7ebf-11ea-8817-d35dc897d0d7.png">

https://reacttraining.com/react-router/web/api/Route/children-func

**Comment by piro0919** [comment]
@syunto07ka 

ちょっと難しかったですかね？
結論から書いてしまうと、自分の想定の範囲では全て`children`で渡してしまって良いはずです。
`children(function)`ではないのが注意です！

`Route`コンポーネントに子コンポーネントを渡す方法は、4つあるみたいですね。

- `children`
- `component`
- `render`
- `children(function)`

`render`についてはdeprecatedしているのでここでは触れません。

`component`で渡す場合は、全ての`route props`が子コンポーネントに渡されます。
(https://reacttraining.com/react-router/web/api/Route/component)

`children(function)`の場合は、`component`で対応しきれない場合に使うっぽいですね。
これは始めて知りました、が、`children`と明示的に書く書き方はどーなんですかね？

`children`の場合は`route props`が渡されないです。
そのため、子コンポーネントがclass構文の場合`route props`に依存しない書き方だとパフォーマンスが良かったわけですね。

ところが、hooksの導入によりわざわざ`route props`を介して子コンポーネントを呼び出す必要がなくなったため、全て`children`による呼び出し方で十分、というのが自分の認識です。
[これ](https://reacttraining.com/react-router/web/api/Hooks/useparams)とかわかりやすいですね。

なので今回の場合は[この書き方](https://reacttraining.com/react-router/web/api/Route)で十分ですね。
