### ISSUE TITLE
react-iconsの導入

### ISSUE THREAD

**Issue by syunto07ka** [syunto07ka/jewelry_box#58]
**Is your feature request related to a problem? Please describe.**
サイトでアイコンを使いたい

**Describe the solution you'd like**
- [react-icons](https://react-icons.netlify.app/#/) を導入する

**Describe alternatives you've considered**
他の方法あるのだろうか 👀

**Additional context**
他のライブラリでのfontawesomeアイコンの使い方とかどうなのだろう

**Comment by piro0919** [comment]
@syunto07ka 

パッケージ名ミスってますね 😄 

× react-icon
○ react-icons

**Comment by piro0919** [comment]
@syunto07ka 

font awesomeの導入方法は[公式サイト](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers)に書かれてますね

**Comment by syunto07ka** [comment]
あ、なるほど別物なのか

https://www.npmjs.com/package/@fortawesome/react-fontawesome

https://www.npmjs.com/package/react-icons

react-iconsはfontawesomeのものも使えるけど、それ以外のものもあると
