### ISSUE TITLE
Reactで画面を作っていくときの手順のベストプラクティスを探る

### ISSUE THREAD

**Issue by syunto07ka** [syunto07ka/jewelry_box#59]
**Is your feature request related to a problem? Please describe.**
そういえばReactでViewを書いていくときにどの順番で実装するのかが分からない

**Describe the solution you'd like**
- Reactでの画面開発の順番で最適な方法を探る

(最初は画面をpagesに書く -> コンポーネントを分解して`src/component` 配下に振り分けていく？)

**Comment by piro0919** [comment]
@syunto07ka 

これはベストプラクティスがあるので、書いちゃいますね。
あくまで理想のフローなので、沿えない部分も多々あると思います。

---

コンポーネント思考における開発フローは、小さいコンポーネントから切るのが絶対です。
つまり、atoms → molecules → organisms → templates → pages と開発を進めていきます。

で、presentational component、つまり atoms ～ templates に対しては、あわせて storybook の story を切ることがテッパンです。

jestについてはコンポーネントに限らず、その時々で切ってやるべきですね。
(自分はjestをそこまで書いたことがないのでアレですが)

---

**Comment by syunto07ka** [comment]
@piro0919 
Organismsやtemplates, pagesの3つをContainer Componentとして扱うといった情報も聞いたことがあるのですが、それは完全な間違いですか？(日本の方が出していたので怪しいとは感じており)

またDanの [Presentational and Container Components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0) の記事の初めの部分で「考えをupdateした。この記事はあまり参考にしないでくれ」と供述があるので、何を見ればいいか悩み始めています。

いろいろ探してみたんですが、今のcomponent liblaryのディレクトリー設計についてちゃんと書いてる記事が見当たらなかったので、何を元に以下の設計に至ったか知りたいなあと思っています。

```
/src
├── components
│   ├── atoms
│   ├── molecules
│   ├── organisms
│   └── templates
```

**Comment by piro0919** [comment]
@syunto07ka 

> Organismsやtemplates, pagesの3つをContainer Componentとして扱うといった情報も聞いたことがあるのですが、それは完全な間違いですか？(日本の方が出していたので怪しいとは感じており)

atomic design的には間違いです。

バケツリレーがイヤで、かつpagesの肥大化を抑えるためにこのような手法を取っているのだとは思いますが、このフローを取るとプロジェクトが破綻すると思います。
ケースバイケースだとは思いますが、まずはatomic designに素直に沿うのが良いかと。

**Comment by piro0919** [comment]
@syunto07ka 

ディレクトリー設計については、ベストプラクティスはないのが現状ですね。
どこの現場も、探り探りでなんとなく分けているのが現状だと思います。

atomic design的な側面から見ると、

> If you find it natural in your codebase, this pattern can be handy.

と書かれている通り、すんなり落とし込むことが可能だと思われます。

自分の場合は、

- ロジックとスタイリングを持つコンポーネントを分けるのは自然だと思った
- atomic design以外のデザインシステムを知らない

というポイントから、そこから落とし込んでディレクトリー設計を行いました。

自分の中でも、今の自分のディレクトリー設計がベストプラクティスだとは思っていません。
が、その一方で、無秩序な状態でコンポーネントを適当に切って保守できなくなるよりは、ベストプラクティスとは言えないかもしれないけれど、ルールのもとにコンポーネント設計を行うほうが100%マシだとは思っています。

なので、例えば

```
/src
  - atoms
  - molecules
  - organisms
  - templates
  - pages
```

という切り方でも全然問題ないと思います。
ただこの切り方をすると、`templates`と`pages`がアルファベット順的に逆になってしまうので、`components`と`containers`を切ったという経緯があります。

なので、大手のOSSのディレクトリーの切り方を真似してみたりするのも全然アリだと思いますよ。 👍

**Comment by piro0919** [comment]
@syunto07ka 

大手OSSの一例です

## [reactjs.org](https://github.com/reactjs/reactjs.org)
react の公式ドキュメントです
意外と複雑な切られ方をしています

## [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate)
react-boilerplateです、過去携わった現場ではこれが使われていました

`app` 以下に `containers` 及び `components` ディレクトリが切られていることが確認できます
また、`containers` については、各コンポーネントのファイル名が `hogehogePage` と suffix が統一されているのも印象的です

**Comment by syunto07ka** [comment]
👀
いろいろ探してみると面白そうですね

**Comment by syunto07ka** [comment]
## 実際の開発イメージ
- ペーパープロトタイピングで実装する画面をざっくりデザイン
- 最小のコンポーネントから実装していく(storybookも切る)
- Pagesに乗せる

### 参考
- https://patternlab-handlebars-preview.netlify.app/?p=all

<img width="681" alt="スクリーンショット 2020-04-24 1 07 16" src="https://user-images.githubusercontent.com/37825725/80122059-027e3380-85c8-11ea-91d2-ab5575f40bb2.png">

**Comment by syunto07ka** [comment]
実装していくイメージつかめたのでこのissueは閉じます！
