### ISSUE TITLE
import を絶対パスで行う

### ISSUE THREAD

**Issue by piro0919** [syunto07ka/jewelry_box#60]
**Is your feature request related to a problem? Please describe.**
相対パスによる import を行う場合、見た目がわるく、バグが出やすい

**Describe the solution you'd like**
絶対パスによる import を行う

**Describe alternatives you've considered**
対応方法は CRA の公式サイトに書かれているので、調べてみてください 👍 

**Additional context**
https://github.com/syunto07ka/jewelry_box/pull/57#issuecomment-615295965

**Comment by syunto07ka** [comment]
https://create-react-app.dev/docs/importing-a-component/#absolute-imports
